-- Exhibitor logos for the app's Exhibitors tab (organiser's logo folder, 3 Oct 2026).
-- Generated by scripts/gen-exhibitor-logos.mjs; the images are served from
-- https://bharataiinnovation.com/images/exhibitors/, so deploy before running this.
--
-- Each row is matched on id AND company_name, and only an empty logo_url is filled,
-- so a logo set later by hand is never overwritten. Safe to run again:
--   npx wrangler d1 execute bharatai-production --remote --file=scripts/sql/exhibitor-logos.sql
-- Exhibitors with no confirmed row on 3 Oct are not here; see the list in the script.

UPDATE exhibitors SET logo_url = 'https://bharataiinnovation.com/images/exhibitors/ai-vie-insights.webp' WHERE id = 9 AND company_name = 'Ai Vie Insights Private Limited' AND COALESCE(logo_url, '') = '';
UPDATE exhibitors SET logo_url = 'https://bharataiinnovation.com/images/exhibitors/algoanalytics.webp' WHERE id = 6 AND company_name = 'Algo Analytics' AND COALESCE(logo_url, '') = '';
UPDATE exhibitors SET logo_url = 'https://bharataiinnovation.com/images/exhibitors/amnex-infotechnologies.webp' WHERE id = 22 AND company_name = 'Amnex technologies' AND COALESCE(logo_url, '') = '';
UPDATE exhibitors SET logo_url = 'https://bharataiinnovation.com/images/exhibitors/ary-soft.webp' WHERE id = 31 AND company_name = 'ary-soft' AND COALESCE(logo_url, '') = '';
UPDATE exhibitors SET logo_url = 'https://bharataiinnovation.com/images/exhibitors/asmadiya-technologies.webp' WHERE id = 12 AND company_name = 'Asmadiya' AND COALESCE(logo_url, '') = '';
UPDATE exhibitors SET logo_url = 'https://bharataiinnovation.com/images/exhibitors/cgi.webp' WHERE id = 5 AND company_name = 'CGI' AND COALESCE(logo_url, '') = '';
UPDATE exhibitors SET logo_url = 'https://bharataiinnovation.com/images/exhibitors/cosmica-telematics.webp' WHERE id = 8 AND company_name = 'COSMICA TELEMATICS PRIVATE LIMITED' AND COALESCE(logo_url, '') = '';
UPDATE exhibitors SET logo_url = 'https://bharataiinnovation.com/images/exhibitors/daten-technology-solutions.webp' WHERE id = 16 AND company_name = 'Daten Intelligenz Software, AIGyan Technologies' AND COALESCE(logo_url, '') = '';
UPDATE exhibitors SET logo_url = 'https://bharataiinnovation.com/images/exhibitors/envista-cyber-defence.webp' WHERE id = 28 AND company_name = 'Envista Cyber Defence' AND COALESCE(logo_url, '') = '';
UPDATE exhibitors SET logo_url = 'https://bharataiinnovation.com/images/exhibitors/eurys-infosystems.webp' WHERE id = 15 AND company_name = 'EURYS infosystemS private limited' AND COALESCE(logo_url, '') = '';
UPDATE exhibitors SET logo_url = 'https://bharataiinnovation.com/images/exhibitors/evoke-technologies.webp' WHERE id = 27 AND company_name = 'Evoke Technologies' AND COALESCE(logo_url, '') = '';
UPDATE exhibitors SET logo_url = 'https://bharataiinnovation.com/images/exhibitors/harrier-information-systems.webp' WHERE id = 25 AND company_name = 'Harrier Information Systems Pvt. Ltd.' AND COALESCE(logo_url, '') = '';
UPDATE exhibitors SET logo_url = 'https://bharataiinnovation.com/images/exhibitors/image-infosystems.webp' WHERE id = 4 AND company_name = 'Image Infosystem' AND COALESCE(logo_url, '') = '';
UPDATE exhibitors SET logo_url = 'https://bharataiinnovation.com/images/exhibitors/indigloo-software.webp' WHERE id = 32 AND company_name = 'Indigloo Software Pvt Ltd' AND COALESCE(logo_url, '') = '';
UPDATE exhibitors SET logo_url = 'https://bharataiinnovation.com/images/exhibitors/intangles.webp' WHERE id = 3 AND company_name = 'Intangles' AND COALESCE(logo_url, '') = '';
UPDATE exhibitors SET logo_url = 'https://bharataiinnovation.com/images/exhibitors/joget.webp' WHERE id = 23 AND company_name = 'Joget INC' AND COALESCE(logo_url, '') = '';
UPDATE exhibitors SET logo_url = 'https://bharataiinnovation.com/images/exhibitors/kadeep-ai.webp' WHERE id = 26 AND company_name = 'kadeep.ai' AND COALESCE(logo_url, '') = '';
UPDATE exhibitors SET logo_url = 'https://bharataiinnovation.com/images/exhibitors/kirusa.webp' WHERE id = 20 AND company_name = 'Kirusa Inc' AND COALESCE(logo_url, '') = '';
UPDATE exhibitors SET logo_url = 'https://bharataiinnovation.com/images/exhibitors/ministry-of-tribal-affairs.webp' WHERE id = 24 AND company_name = 'Ministry of Tribal Affairs' AND COALESCE(logo_url, '') = '';
UPDATE exhibitors SET logo_url = 'https://bharataiinnovation.com/images/exhibitors/nobroker.webp' WHERE id = 10 AND company_name = 'NoBroker Technologies Solutions Private Limited' AND COALESCE(logo_url, '') = '';
UPDATE exhibitors SET logo_url = 'https://bharataiinnovation.com/images/exhibitors/oranje-ai.webp' WHERE id = 14 AND company_name = 'ORANJE AI PRIVATE LIMITED' AND COALESCE(logo_url, '') = '';
UPDATE exhibitors SET logo_url = 'https://bharataiinnovation.com/images/exhibitors/origin-ai.webp' WHERE id = 19 AND company_name = 'Origin AI' AND COALESCE(logo_url, '') = '';
UPDATE exhibitors SET logo_url = 'https://bharataiinnovation.com/images/exhibitors/paisani-technology-services.webp' WHERE id = 13 AND company_name = 'Paisani Technology Services' AND COALESCE(logo_url, '') = '';
UPDATE exhibitors SET logo_url = 'https://bharataiinnovation.com/images/exhibitors/phoebetal-technologies.webp' WHERE id = 30 AND company_name = 'Phoebetal Technologies Pvt Ltd' AND COALESCE(logo_url, '') = '';
UPDATE exhibitors SET logo_url = 'https://bharataiinnovation.com/images/exhibitors/qapitol-ai.webp' WHERE id = 2 AND company_name = 'Qapitol AI' AND COALESCE(logo_url, '') = '';
UPDATE exhibitors SET logo_url = 'https://bharataiinnovation.com/images/exhibitors/redferns-tech.webp' WHERE id = 29 AND company_name = 'RedFerns Tech Private Limited' AND COALESCE(logo_url, '') = '';
UPDATE exhibitors SET logo_url = 'https://bharataiinnovation.com/images/exhibitors/saranyu-technologies.webp' WHERE id = 11 AND company_name = 'Saranyu Technologies' AND COALESCE(logo_url, '') = '';
UPDATE exhibitors SET logo_url = 'https://bharataiinnovation.com/images/exhibitors/seem-fintech-and-sustainability.webp' WHERE id = 7 AND company_name = 'Seem Fintech & Sustainability Pvt Ltd' AND COALESCE(logo_url, '') = '';
UPDATE exhibitors SET logo_url = 'https://bharataiinnovation.com/images/exhibitors/wyn-labs.webp' WHERE id = 17 AND company_name = 'Wyn Labs' AND COALESCE(logo_url, '') = '';
UPDATE exhibitors SET logo_url = 'https://bharataiinnovation.com/images/exhibitors/zanopy-ai.webp' WHERE id = 21 AND company_name = 'Zanopy AI' AND COALESCE(logo_url, '') = '';
