-- Migration 0029: private boardrooms -- inventory and bookings.
--
-- The homepage has advertised four WTC Mumbai boardrooms since launch under the
-- promise "Rooms are subject to availability on 20-21 November 2026", and nothing
-- anywhere tracks that availability. The public CTA deliberately routes an enquiry
-- to the contact form -- rooms are charged by the hour plus GST, so the price has
-- to be quoted, not self-served -- but the team still has to answer "is Jasmine
-- free at 11 on the 20th?" and today the only answer is somebody's memory. This is
-- the ledger behind that promise, not a shop front.
--
-- WHY BOOKINGS-AS-ROWS AND NOT A PRE-GENERATED SLOT GRID
--   The rooms are priced PER HOUR, so the hour is already the commercial atom.
--   Fixing the booking atom at one hour is what makes UNIQUE(room_id, slot_start)
--   a real guarantee: SQLite has no exclusion constraint, so overlap between
--   variable-length bookings cannot be enforced declaratively at all. A two-hour
--   reservation is therefore two rows sharing a group_ref, not one row with a
--   duration. A pre-generated grid (4 rooms x 2 days x 9 hours = 72 rows) would
--   have to be regenerated by hand -- another --remote execute -- every time the
--   hours change, and it cannot keep a cancellation for audit while also freeing
--   the hour. The partial index below does both.
--
-- Room data below is copied verbatim from public/index.html (card text + image alt
-- attributes). Nothing here is invented. Note that Board Room 4 seats 12 yet is
-- priced above Board Room 3 which seats 20 -- that is what the site publishes.
--
-- No FOREIGN KEY clauses, following 0021/0027/0028: a FK on attendee_id would make
-- the existing DELETE FROM attendees in the admin panel start failing.

CREATE TABLE IF NOT EXISTS meeting_rooms (
  id         INTEGER PRIMARY KEY AUTOINCREMENT,
  event_id   INTEGER NOT NULL DEFAULT 1,
  slug       TEXT    NOT NULL UNIQUE,   -- stable key, independent of the row id
  label      TEXT    NOT NULL,          -- what the site calls it
  wtc_name   TEXT    NOT NULL,          -- what the venue calls it, for signage and the WTC
  layout     TEXT,                      -- NULL where the site does not state one
  capacity   INTEGER NOT NULL,
  price_inr  INTEGER NOT NULL,          -- per hour, exclusive of GST
  image_url  TEXT,
  sort_order INTEGER NOT NULL DEFAULT 0,
  is_active  INTEGER NOT NULL DEFAULT 1,
  created_at TEXT    DEFAULT CURRENT_TIMESTAMP
);

INSERT OR IGNORE INTO meeting_rooms
  (event_id, slug, label, wtc_name, layout, capacity, price_inr, image_url, sort_order) VALUES
  (1, 'board-room-1', 'Board Room 1', 'Board Room',      'U-shape', 25, 15000, '/images/venue-boardroom-1.jpg', 1),
  (1, 'board-room-2', 'Board Room 2', 'Committee Room',  NULL,      30, 15000, '/images/venue-boardroom-2.jpg', 2),
  (1, 'board-room-3', 'Board Room 3', 'Jasmine Room',    'U-shape', 20, 10000, '/images/venue-boardroom-3.jpg', 3),
  (1, 'board-room-4', 'Board Room 4', 'Conference Room', NULL,      12, 15000, '/images/venue-boardroom-4.jpg', 4);

-- One row per room-hour. slot_start is always 'YYYY-MM-DD HH:00' -- the same
-- 'YYYY-MM-DD HH:MM' text shape sessions.start_time uses, so the two sort and
-- compare together without conversion.
CREATE TABLE IF NOT EXISTS room_bookings (
  id            INTEGER PRIMARY KEY AUTOINCREMENT,
  event_id      INTEGER NOT NULL DEFAULT 1,
  room_id       INTEGER NOT NULL,
  slot_date     TEXT    NOT NULL,               -- 'YYYY-MM-DD', denormalised for the day grid
  slot_start    TEXT    NOT NULL,               -- 'YYYY-MM-DD HH:00'
  slot_end      TEXT    NOT NULL,               -- 'YYYY-MM-DD HH:00', always +1h
  group_ref     TEXT,                           -- ties the consecutive hours of one reservation
  kind          TEXT    NOT NULL DEFAULT 'booking',  -- booking | block
  attendee_id   INTEGER,                        -- NULL for an admin-created block
  meeting_id    INTEGER,                        -- set when the hour was booked from a meeting request
  title         TEXT,
  headcount     INTEGER,
  notes         TEXT,
  contact_name  TEXT,
  contact_email TEXT,
  contact_phone TEXT,
  price_inr     INTEGER NOT NULL DEFAULT 0,     -- snapshot of the rate at booking time
  status        TEXT    NOT NULL DEFAULT 'held',    -- held | confirmed | cancelled | rejected
  created_by    TEXT,
  created_at    TEXT    DEFAULT CURRENT_TIMESTAMP,
  updated_at    TEXT    DEFAULT CURRENT_TIMESTAMP,
  cancelled_at  TEXT
);

-- THE GUARANTEE. Two people cannot hold the same room-hour, whatever the API does
-- or fails to do. Partial, so a cancelled or rejected row keeps its history while
-- releasing the hour -- which a booking_id column on a pre-generated grid cannot.
CREATE UNIQUE INDEX IF NOT EXISTS ux_room_bookings_slot
  ON room_bookings(room_id, slot_start)
  WHERE status IN ('held', 'confirmed');

CREATE INDEX IF NOT EXISTS idx_room_bookings_day      ON room_bookings(slot_date, room_id, slot_start);
CREATE INDEX IF NOT EXISTS idx_room_bookings_attendee ON room_bookings(attendee_id, slot_start);
CREATE INDEX IF NOT EXISTS idx_room_bookings_group    ON room_bookings(group_ref);
CREATE INDEX IF NOT EXISTS idx_room_bookings_meeting  ON room_bookings(meeting_id);
